# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# File: .github/workflows/repo-sync.yml

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "git@github.com:Christy99cc/blog.git"
        source_branch: "master/docs/*"
        destination_repo: "git@github.com:Christy99cc/Christy99cc.github.io.git"
        destination_branch: "master/*"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
