
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# File: .github/workflows/repo-sync.yml

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Source Repo
      working-directory: /tmp
      env:
        SOURCE_REPO: https://Christy99cc:${{ secrets.ACCESS_TOKEN }}@github.com/Christy99cc/blog.git
        SOURCE_REPO_NAME: blog
        SOURCE_BRANCH: master
        DESTINATION_REPO: https://Christy99cc:${{ secrets.ACCESS_TOKEN }}@github.com/Christy99cc/Christy99cc.github.io.git
        DESTINATION_BRANCH: master
      run: |
        git clone $SOURCE_REPO && cd $SOURCE_REPO_NAME && rm -rf .git
        npm install && sudo npm install hexo -g
        hexo generate && cd docs &&  git init
        git remote add origin $DESTINATION_REPO && git add . && git commit -m "Update blog" && git push -f origin $DESTINATION_BRANCH
